version: "3"

services:
  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ../src:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ../data/data.sql:/docker-entrypoint-initdb.d/data.sql
